version: '3.8'
services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: skratzsch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - skratzsch-network

  mongo:
    image: mongo:7.0.5
    ports:
      - "27017:27017"
    networks:
      - skratzsch-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - skratzsch-network

networks:
  skratzsch-network:
    driver: bridge
